require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
require('core.plugin_config.cmp')
require('core.plugin_config.null_ls')
require('core.plugin_config.prettier')
require('core.plugin_config.luasnip')
require('core.plugin_config.tree')
